# Generated by Django 3.1 on 2020-09-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': '1. Staff',
            },
        ),
    ]
