# Generated by Django 3.1 on 2020-09-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0004_auto_20200913_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[('1', 'Approved'), ('2', 'On Hold'), ('3', 'Rejected')], default='2', max_length=20),
        ),
    ]
