# Generated by Django 3.1 on 2020-09-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0006_connection_connection_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='connection_Number',
        ),
        migrations.AddField(
            model_name='connection',
            name='connection_number',
            field=models.CharField(blank=True, default='4739144735', editable=False, max_length=10, unique=True),
        ),
    ]
