# Generated by Django 3.1 on 2020-09-18 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0010_auto_20200918_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasReffling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reffeling_size', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'GasReffling',
                'verbose_name_plural': '3.Gas Reffling',
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': '4.Booking'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(blank=True, default='vqtT5ipf', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_number',
            field=models.CharField(blank=True, default='Rco7HNk9', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reffeling_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas.gasreffling'),
        ),
    ]
