# Generated by Django 3.1 on 2020-09-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0011_auto_20200918_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(blank=True, default='qVKghz4z', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_number',
            field=models.CharField(blank=True, default='qkivakMg', editable=False, max_length=10, unique=True),
        ),
    ]
