# Generated by Django 3.1 on 2020-09-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0012_auto_20200918_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='reffeling_size',
            new_name='reffeling',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(blank=True, default='0Pq0naZ9', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_number',
            field=models.CharField(blank=True, default='9gItMrpv', editable=False, max_length=10, unique=True),
        ),
    ]
