# Generated by Django 3.1 on 2020-09-22 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0015_auto_20200918_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(blank=True, default='797E4FAFAC4', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_number',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=10, unique=True),
        ),
    ]
