# Generated by Django 3.1 on 2020-09-22 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0016_auto_20200922_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=10, unique=True),
        ),
    ]
