# Generated by Django 3.1 on 2020-09-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0017_auto_20200922_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasreffiling',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gas'),
        ),
    ]
