# Generated by Django 3.1 on 2020-09-22 15:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(max_length=250)),
                ('card_number', models.CharField(max_length=255)),
                ('expiration', models.DateTimeField()),
                ('security_code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('postal_code', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment_credit_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PaymentCreditCard',
                'verbose_name_plural': '3. PaymentCreditCard',
            },
        ),
    ]
